name: acoustic_event_detector
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.14.1+3
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  flutter_bloc: ^6.0.6
  flutter_map: ^0.10.1+1
  geocoding: ^1.0.4+1
  json_annotation: ^3.1.0
  meta: ^1.2.3
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  json_serializable: ^3.5.0

flutter:

  uses-material-design: true

flutter_intl:
  enabled: true
